version: '3.7'

services:
  mysql-test:
    container_name: mysql-test
    image: mysql:8.0
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    env_file:
      - .env
    environment:
      - 'MYSQL_DATABASE=${DATABASE_NAME}'
      - 'MYSQL_USER=${DATABASE_USER}'
      - 'MYSQL_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
    ports:
      - '${DATABASE_PORT}:3306'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./tmp/mysql_test:/var/lib/mysql
    networks:
      - proxy-net-test

  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./tmp/redis_test:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    networks:
      - proxy-net-test

  webapi-test:
    container_name: webapi-test
    build:
      context: .
      target: backenddev
    env_file:
      - .env
    ports:
      - '${DJANGO_PORT}:${DJANGO_PORT}'
    volumes:
      - ./:/app
      - ${FIREBASE_ADMIN_CONFIG_PATH}:/app/configs/firebase/config.json
    depends_on:
      mysql-test:
        condition: service_healthy
    networks:
      - proxy-net-test

  celery-test:
    build:
      context: .
      target: backenddev
    container_name: celery-test
    restart: unless-stopped
    command: celery -A project worker -B -l INFO
    volumes:
      - ./:/app
      - ${FIREBASE_ADMIN_CONFIG_PATH}:/app/configs/firebase/config.json
    env_file:
      - .env
    depends_on:
      - webapi-test
      - redis-test
    networks:
      - proxy-net-test
networks:
  proxy-net-test:
    name: internal_network_for_test
