# Generated by Django 5.0.6 on 2024-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=31, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('gender', models.SmallIntegerField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users_users',
            },
        ),
    ]
