name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Export GitHub Secrets to .env file
      run: |
        echo '${{ toJson(vars) }}' > vars.json
        cat vars.json | jq -r 'to_entries | .[] | "echo " + .key + "=" + .value + " >> .env"' > export_env.sh
        bash export_env.sh
    - name: Validate .env file
      run: cat .env
    - name: Deploy
      run: |
        docker-compose down && docker-compose build && docker-compose up -d --force-recreate
