name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    env:
      DB_HOST: ${{ vars.DB_HOST }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_PORT: ${{ vars.DB_PORT }}
      NGINX_PORT: ${{ vars.NGINX_PORT }}
      PRODUCTION: ${{ vars.PRODUCTION }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file for Docker Compose
      run: |
        echo DB_HOST=$DB_HOST >> .env
        echo DB_NAME=$DB_NAME >> .env
        echo DB_PASS=$DB_PASS >> .env:
        echo DB_PORT=$DB_PORT >> .env:
        echo NGINX_PORT=$NGINX_PORT >> .env:
        echo PRODUCTION=$PRODUCTION >> .env:
    - name: Validate .env file
      run: cat .env
    - name: Deploy
      run: |
        docker-compose down && docker-compose build && docker-compose up -d --force-recreate
